<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:DejaVu Sans,sans-serif;font-size:11px;color:#111}h1{font-size:18px;margin:0 0 4px}h2{font-size:13px;margin:14px 0 6px}.muted{color:#555}.meta{width:100%;margin-bottom:10px}.meta td{vertical-align:top}.tbl{width:100%;border-collapse:collapse}.tbl th,.tbl td{border:1px solid #999;padding:4px}.tbl th{background:#eee} .small{font-size:10px}</style></head><body>
<table class="meta"><tr><td><h1>SIPANDA-KPH - Rekap Pekerjaan</h1><div class="muted">Periode: {{ $periodeLabel }}</div><div class="muted">Kode: {{ $validation->report_code }}</div><div class="muted">Dibuat: {{ $validation->generated_at->format('d-m-Y H:i') }} oleh {{ $validation->generatedBy->name ?? '-' }}</div></td><td style="text-align:right">{!! $validationQrSvg !!}<div class="small">Scan untuk validasi dokumen</div></td></tr></table>
<h2>Ringkasan Tugas</h2><table class="tbl"><tr><th>Total</th><th>Selesai</th><th>Belum</th><th>Menunggu Verifikasi</th><th>Revisi</th><th>Terlambat</th></tr><tr><td>{{ $summaryTugas['total_tugas'] }}</td><td>{{ $summaryTugas['tugas_selesai'] }}</td><td>{{ $summaryTugas['tugas_belum_dikerjakan'] + $summaryTugas['tugas_sedang_dikerjakan'] + $summaryTugas['tugas_menunggu_verifikasi'] + $summaryTugas['tugas_revisi'] }}</td><td>{{ $summaryTugas['tugas_menunggu_verifikasi'] }}</td><td>{{ $summaryTugas['tugas_revisi'] }}</td><td>{{ $summaryTugas['tugas_terlambat'] }}</td></tr></table>
<h2>Ringkasan Catatan</h2><table class="tbl"><tr><th>Total</th><th>Menunggu</th><th>Disetujui</th><th>Revisi</th><th>Ditolak</th></tr><tr><td>{{ $summaryCatatan['total_catatan'] }}</td><td>{{ $summaryCatatan['catatan_menunggu_verifikasi'] }}</td><td>{{ $summaryCatatan['catatan_disetujui'] }}</td><td>{{ $summaryCatatan['catatan_revisi'] }}</td><td>{{ $summaryCatatan['catatan_ditolak'] }}</td></tr></table>
<h2>Rekap Per Pegawai</h2><table class="tbl"><tr><th>Pegawai</th><th>Unit</th><th>Total</th><th>Selesai</th><th>Belum</th><th>Terlambat</th><th>Catatan</th><th>Disetujui</th></tr>@foreach($rekapPegawai as $r)<tr><td>{{ $r->nama_pegawai }}</td><td>{{ $r->unit_kerja ?? '-' }}</td><td>{{ $r->total_tugas }}</td><td>{{ $r->tugas_selesai }}</td><td>{{ $r->tugas_belum_selesai }}</td><td>{{ $r->tugas_terlambat }}</td><td>{{ $r->total_catatan }}</td><td>{{ $r->catatan_disetujui }}</td></tr>@endforeach</table>
<h2>Rekap Per Unit Kerja</h2><table class="tbl"><tr><th>Unit</th><th>Total</th><th>Selesai</th><th>Belum</th><th>Terlambat</th><th>%</th></tr>@foreach($rekapUnitKerja as $u)<tr><td>{{ $u->nama_unitkerja }}</td><td>{{ $u->total_tugas }}</td><td>{{ $u->tugas_selesai }}</td><td>{{ $u->tugas_belum_selesai }}</td><td>{{ $u->tugas_terlambat }}</td><td>{{ $u->persentase_selesai }}%</td></tr>@endforeach</table>
<h2>Detail Tugas</h2><table class="tbl"><tr><th>Tanggal</th><th>Pegawai</th><th>Unit</th><th>Judul</th><th>Prioritas</th><th>Deadline</th><th>Status</th><th>Progres</th></tr>@foreach($daftarTugas as $t)<tr><td>{{ optional($t->tugas->tanggal_tugas)->format('d-m-Y') ?? '-' }}</td><td>{{ $t->pegawai->user->name ?? '-' }}</td><td>{{ $t->pegawai->unitkerja->nama_unitkerja ?? '-' }}</td><td>{{ $t->tugas->judul ?? '-' }}</td><td>{{ $t->tugas->prioritas ?? '-' }}</td><td>{{ optional($t->tugas->deadline)->format('d-m-Y') ?? '-' }}</td><td>{{ $t->status }}</td><td>{{ (int)($t->progres_persen ?? 0) }}%</td></tr>@endforeach</table>
<h2>Detail Catatan Kegiatan</h2><table class="tbl"><tr><th>Tanggal</th><th>Pegawai</th><th>Tugas</th><th>Hasil</th><th>Status Verifikasi</th></tr>@foreach($daftarCatatan as $c)<tr><td>{{ optional($c->tanggal_kegiatan)->format('d-m-Y') ?? '-' }}</td><td>{{ $c->pegawai->user->name ?? '-' }}</td><td>{{ $c->penugasan->tugas->judul ?? '-' }}</td><td>{{ \Illuminate\Support\Str::limit($c->hasil_kegiatan ?? $c->deskripsi ?? '-',80) }}</td><td>{{ $c->status_verifikasi_label }}</td></tr>@endforeach</table>
<div class="small muted" style="margin-top:8px">Validasi: {{ $validation->validationUrl() }}</div>
</body></html>
